### Create a film 
POST http://localhost:3000/films
Content-Type: application/json

{
    "title" : "Inception",
    "director" : "Christopher Nolan",
    "duration" : 164
}

### Read all films
GET http://localhost:3000/films

### Read a single pizza
@baseUrl = http://localhost:3000
GET {{baseUrl}}/films/2

### ### Read all films >= 106 minutes
Get {{baseUrl}}/films/?minimum-duration=107